### ISSUE TITLE
Choose a project name

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/project-management#1]
We need to choose a name for our project.
## Resource(s)
- Producing Open Source Software - Chapter 2 Getting Started - [Choose a Good Name](http://producingoss.com/en/getting-started.html#choosing-a-name)
## Tasks
- [ ] Create a list of name options, based on brainstorming discussion
- [ ] Choose popular name(s) from the list to narrow the choices
- [ ] Check domain, social media, and trademark availability
- [ ] Check search engine saturation of name keyword(s)
- [ ] Decide on final project name
