### ISSUE TITLE
Choose sourcecode license

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/project-management#2]
We need an open-source license for the project.
## Review material(s)
- Producing Open Source Software - Chapter 2 [Choosing a License and Applying It](http://producingoss.com/en/license-quickstart.html)
## Task
- [ ] Discuss license choices and implications
- [ ] Decide on a sourcecode license
- [ ] Add sourcecode license terms to project root directory

**Comment by brylie** [comment]
In order to keep this decision participatory and focused, I propose we consider two license options and choose one together:
- [MIT](http://opensource.org/licenses/MIT)
- [AGPL](http://opensource.org/licenses/AGPL-3.0)

**Comment by brylie** [comment]
I would prefer that we protect this project sourcecode from being subsumed into closed-source (or proprietary) software.

> If you don't want your code to be used in proprietary programs, use the [GNU General Public License, version 3](http://gnu.org/licenses/gpl.html) - _Producing Open Source Software - Chapter 2 - Choosing a License and Applying It_

Additionally, we are producing software that will be run on servers, in addition to web browsers.

> If users interact with your code primarily over a network ... then consider using the [GNU Affero GPL](http://www.gnu.org/licenses/agpl-3.0.en.html) instead. - _Producing Open Source Software - Chapter 2 - Choosing a License and Applying It_

My preference is that we protect this project sourcecode under the [GNU AGPL v3](http://www.gnu.org/licenses/agpl-3.0.en.html), as a commonwealth resource.
