### ISSUE TITLE
Goals/Milestones

### ISSUE THREAD

**Issue by brylie** [meteorcrowd/project-management#23]
Goals and milestones help collaborators see the big picture, while working on smaller tasks.
- [ ] Determine how to support goals/milestones
- [ ] Implement basic schema
- [ ] Create basic views
